[package]
name = "p2saveconvert"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
anyhow = "1.0"
maplit = "1.0"
lazy_static = "1.4"
itertools = "0.10"

[profile.release]
lto = true
